
var Stockfish = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(Stockfish) {
  Stockfish = Stockfish || {};


function e(){g.buffer!=m&&q(g.buffer);return aa}function v(){g.buffer!=m&&q(g.buffer);return ba}function w(){g.buffer!=m&&q(g.buffer);return ca}function z(){g.buffer!=m&&q(g.buffer);return da}function ea(){g.buffer!=m&&q(g.buffer);return fa}null;var A;A||(A=typeof Stockfish !== 'undefined' ? Stockfish : {});var ha,ia;A.ready=new Promise(function(a,b){ha=a;ia=b});A.postCustomMessage=a=>{for(let b of B.Pa)b.postMessage({cmd:"custom",userData:a})};
class ja{constructor(){this.Va=null;this.Qa=[]}async get(){return 0<this.Qa.length?this.Qa.shift():await new Promise(a=>this.Va=a)}put(a){this.Va?(this.Va(a),this.Va=null):this.Qa.push(a)}}A.queue=new ja;A.onCustomMessage=a=>{A.queue.put(a)};A.postMessage=A.postCustomMessage;const ka=[];A.addMessageListener=a=>{ka.push(a)};A.removeMessageListener=a=>{a=ka.indexOf(a);0<=a&&ka.splice(a,1)};A.print=A.printErr=a=>{if(0===ka.length)console.log(a);else for(let b of ka)b(a)};A.terminate=()=>{B.$b()};
var la={},D;for(D in A)A.hasOwnProperty(D)&&(la[D]=A[D]);var ma=[],na="./this.program";function oa(a,b){throw b;}var pa="object"===typeof window,E="function"===typeof importScripts,F="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node,G=A.ENVIRONMENT_IS_PTHREAD||!1,J="";function qa(a){return A.locateFile?A.locateFile(a,J):J+a}var ra,sa,ta,K,L;
if(F){J=E?require("path").dirname(J)+"/":__dirname+"/";ra=function(a,b){K||(K=require("fs"));L||(L=require("path"));a=L.normalize(a);return K.readFileSync(a,b?null:"utf8")};ta=function(a){a=ra(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};sa=function(a,b,c){K||(K=require("fs"));L||(L=require("path"));a=L.normalize(a);K.readFile(a,function(d,f){d?c(d):b(f.buffer)})};1<process.argv.length&&(na=process.argv[1].replace(/\\/g,"/"));ma=process.argv.slice(2);process.on("uncaughtException",
function(a){if(!(a instanceof ua))throw a;});process.on("unhandledRejection",M);oa=function(a,b){if(va())throw process.exitCode=a,b;process.exit(a)};A.inspect=function(){return"[Emscripten Module object]"};var wa;try{wa=require("worker_threads")}catch(a){throw console.error('The "worker_threads" module is not supported in this node.js build - perhaps a newer version is needed?'),a;}global.Worker=wa.Worker}else if(pa||E)E?J=self.location.href:"undefined"!==typeof document&&document.currentScript&&
(J=document.currentScript.src),_scriptDir&&(J=_scriptDir),0!==J.indexOf("blob:")?J=J.substr(0,J.lastIndexOf("/")+1):J="",F?(ra=function(a,b){K||(K=require("fs"));L||(L=require("path"));a=L.normalize(a);return K.readFileSync(a,b?null:"utf8")},ta=function(a){a=ra(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},sa=function(a,b,c){K||(K=require("fs"));L||(L=require("path"));a=L.normalize(a);K.readFile(a,function(d,f){d?c(d):b(f.buffer)})}):(ra=function(a){var b=new XMLHttpRequest;b.open("GET",
a,!1);b.send(null);return b.responseText},E&&(ta=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),sa=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)});F&&"undefined"===typeof performance&&(global.performance=require("perf_hooks").performance);
var xa=A.print||console.log.bind(console),N=A.printErr||console.warn.bind(console);for(D in la)la.hasOwnProperty(D)&&(A[D]=la[D]);la=null;A.arguments&&(ma=A.arguments);A.thisProgram&&(na=A.thisProgram);A.quit&&(oa=A.quit);var ya,za;A.wasmBinary&&(za=A.wasmBinary);var noExitRuntime=A.noExitRuntime||!0;"object"!==typeof WebAssembly&&M("no native wasm support detected");var g,Aa,Ba=!1,Ca;function assert(a,b){a||M("Assertion failed: "+b)}
function Da(a){var b=new TextDecoder(a);this.decode=function(c){c.buffer instanceof SharedArrayBuffer&&(c=new Uint8Array(c));return b.decode.call(b,c)}}var Ea="undefined"!==typeof TextDecoder?new Da("utf8"):void 0;
function Fa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Ea)return Ea.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var h=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|h);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|h<<6|k:(f&7)<<18|h<<12|k<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function O(a){return a?Fa(v(),a,void 0):""}
function Ga(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var h=0;h<a.length;++h){var k=a.charCodeAt(h);if(55296<=k&&57343>=k){var p=a.charCodeAt(++h);k=65536+((k&1023)<<10)|p&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-f}
function Ha(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new Da("utf-16le");function Ia(a){var b=Ha(a)+1,c=Ja(b);Ga(a,e(),c,b);return c}function Ka(a,b){e().set(a,b)}var m,aa,ba,La,ca,da,fa;G&&(m=A.buffer);
function q(a){m=a;A.HEAP8=aa=new Int8Array(a);A.HEAP16=La=new Int16Array(a);A.HEAP32=ca=new Int32Array(a);A.HEAPU8=ba=new Uint8Array(a);A.HEAPU16=new Uint16Array(a);A.HEAPU32=da=new Uint32Array(a);A.HEAPF32=new Float32Array(a);A.HEAPF64=fa=new Float64Array(a)}var Ma=A.INITIAL_MEMORY||134217728;
if(G)g=A.wasmMemory,m=A.buffer;else if(A.wasmMemory)g=A.wasmMemory;else if(g=new WebAssembly.Memory({initial:Ma/65536,maximum:32768,shared:!0}),!(g.buffer instanceof SharedArrayBuffer))throw N("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),F&&console.log("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)"),
Error("bad memory");g&&(m=g.buffer);Ma=m.byteLength;q(m);var Na=[],Oa=[],Pa=[],Qa=[],Ra=0;function va(){return noExitRuntime||0<Ra}function Sa(){G||(A.noFSInit||P.lb.Pb||P.lb(),P.vc=!1,Ta(Oa))}function Ua(){var a=A.preRun.shift();Na.unshift(a)}var Va=0,Wa=null,Xa=null;function Ya(){Va++;A.monitorRunDependencies&&A.monitorRunDependencies(Va)}function Za(){Va--;A.monitorRunDependencies&&A.monitorRunDependencies(Va);if(0==Va&&(null!==Wa&&(clearInterval(Wa),Wa=null),Xa)){var a=Xa;Xa=null;a()}}
A.preloadedImages={};A.preloadedAudios={};function M(a){if(G)postMessage({cmd:"onAbort",arg:a});else if(A.onAbort)A.onAbort(a);N(a);Ba=!0;Ca=1;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ia(a);throw a;}function $a(){return Q.startsWith("data:application/octet-stream;base64,")}var Q;Q="stockfish.wasm";$a()||(Q=qa(Q));
function ab(){var a=Q;try{if(a==Q&&za)return new Uint8Array(za);if(ta)return ta(a);throw"both async and sync fetching of the wasm failed";}catch(b){M(b)}}function bb(){return za||!pa&&!E||"function"!==typeof fetch?Promise.resolve().then(function(){return ab()}):fetch(Q,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Q+"'";return a.arrayBuffer()}).catch(function(){return ab()})}var S,T,cb={};
function Ta(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(A);else{var c=b.pc;"number"===typeof c?void 0===b.kb?dynCall_v.call(null,c):dynCall_vi.apply(null,[c,b.kb]):c(void 0===b.kb?null:b.kb)}}}
function db(a,b){if(0>=a||a>e().length||a&1||0>b)return-28;if(0==b)return 0;2147483647<=b&&(b=Infinity);var c=Atomics.load(w(),eb>>2),d=0;if(c==a&&Atomics.compareExchange(w(),eb>>2,c,0)==c&&(--b,d=1,0>=b))return 1;a=Atomics.notify(w(),a>>2,b);if(0<=a)return a+d;throw"Atomics.notify returned an unexpected value "+a;}A._emscripten_futex_wake=db;
function fb(a){if(G)throw"Internal Error! cleanupThread() can only ever be called from main application thread!";if(!a)throw"Internal Error! Null pthread_ptr in cleanupThread!";var b=B.Ga[a];b&&(w()[a+8>>2]=0,B.zb(b.worker))}function gb(a){hb(a)}A._exit=gb;function ib(a){a instanceof ua||"unwind"==a||(N("exception thrown: "+a),oa(1,a))}
var B={Ta:[],Pa:[],bc:[],Nd:function(){},Xc:function(){B.receiveObjectTransfer=B.pd;B.threadInit=B.zc;B.setExitStatus=B.td},Ga:{},ac:[],td:function(a){Ca=a},$b:function(){for(var a in B.Ga){var b=B.Ga[a];b&&b.worker&&B.zb(b.worker)}B.Ga={};for(a=0;a<B.Ta.length;++a){var c=B.Ta[a];c.terminate()}B.Ta=[];for(a=0;a<B.Pa.length;++a)c=B.Pa[a],b=c.Oa,c.terminate(),B.Kb(b);B.Pa=[]},Kb:function(a){a&&(a.gb&&jb(a.gb),a.gb=0,a.Gb&&a.$a&&jb(a.$a),a.$a=0,a.worker&&(a.worker.Oa=null))},zb:function(a){B.rd(function(){delete B.Ga[a.Oa.gb];
B.Ta.push(a);B.Pa.splice(B.Pa.indexOf(a),1);B.Kb(a.Oa);a.Oa=void 0})},rd:function(a){w()[kb>>2]=0;try{a()}finally{w()[kb>>2]=1}},pd:function(){},zc:function(){for(var a in B.bc)B.bc[a]()},ad:function(a,b){a.onmessage=function(c){var d=c.data,f=d.cmd;a.Oa&&(B.Pc=a.Oa.gb);if(d.targetThread&&d.targetThread!=lb()){var h=B.Ga[d.Zd];h?h.worker.postMessage(c.data,d.transferList):N('Internal error! Worker sent a message "'+f+'" to target pthread '+d.targetThread+", but that thread no longer exists!")}else if("processQueuedMainThreadWork"===
f)mb();else if("spawnThread"===f)nb(c.data);else if("cleanupThread"===f)fb(d.thread);else if("killThread"===f){c=d.thread;if(G)throw"Internal Error! killThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in killThread!";w()[c+8>>2]=0;d=B.Ga[c];delete B.Ga[c];d.worker.terminate();B.Kb(d);B.Pa.splice(B.Pa.indexOf(d.worker),1);d.worker.Oa=void 0}else if("cancelThread"===f){c=d.thread;if(G)throw"Internal Error! cancelThread() can only ever be called from main application thread!";
if(!c)throw"Internal Error! Null pthread_ptr in cancelThread!";B.Ga[c].worker.postMessage({cmd:"cancel"})}else if("loaded"===f)a.loaded=!0,b&&b(a),a.pb&&(a.pb(),delete a.pb);else if("print"===f)xa("Thread "+d.threadId+": "+d.text);else if("printErr"===f)N("Thread "+d.threadId+": "+d.text);else if("alert"===f)alert("Thread "+d.threadId+": "+d.text);else if("detachedExit"===f)B.zb(a);else if("exitProcess"===f)try{hb(d.returnCode)}catch(k){ib(k)}else if("cancelDone"===f)B.zb(a);else if("setimmediate"===
c.data.target)a.postMessage(c.data);else if("onAbort"===f){if(A.onAbort)A.onAbort(d.arg)}else N("worker sent an unknown command "+f);B.Pc=void 0};a.onerror=function(c){N("pthread sent an error! "+c.filename+":"+c.lineno+": "+c.message);throw c;};F&&(a.on("message",function(c){a.onmessage({data:c})}),a.on("error",function(c){a.onerror(c)}),a.on("detachedExit",function(){}));a.postMessage({cmd:"load",urlOrBlob:A.mainScriptUrlOrBlob||_scriptDir,wasmMemory:g,wasmModule:Aa})},Ec:function(){var a=qa("stockfish.worker.js");
B.Ta.push(new Worker(a))},Vc:function(){0==B.Ta.length&&(B.Ec(),B.ad(B.Ta[0]));return B.Ta.pop()}};A.establishStackSpace=function(a,b){ob(a,b);pb(a)};A.invokeEntryPoint=function(a,b){return qb.apply(null,[a,b])};var rb;rb=F?function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:G?function(){return performance.now()-A.__performance_now_clock_drift}:function(){return performance.now()};
function nb(a){if(G)throw"Internal Error! spawnThread() can only ever be called from main application thread!";var b=B.Vc();if(!b)return 6;if(void 0!==b.Oa)throw"Internal error!";if(!a.yb)throw"Internal error, no pthread ptr!";B.Pa.push(b);var c=a.$a+a.fb,d=B.Ga[a.yb]={worker:b,$a:a.$a,fb:a.fb,Gb:a.Gb,gb:a.yb},f=d.gb>>2;Atomics.store(z(),f+15,a.detached);Atomics.store(z(),f+19,a.fb);Atomics.store(z(),f+18,c);Atomics.store(z(),f+25,a.fb);Atomics.store(z(),f+27,c);Atomics.store(z(),f+28,a.detached);
b.Oa=d;var h={cmd:"run",start_routine:a.ud,arg:a.kb,threadInfoStruct:a.yb,stackBase:a.$a,stackSize:a.fb};b.pb=function(){h.time=performance.now();b.postMessage(h,a.Ad)};b.loaded&&(b.pb(),delete b.pb);return 0}
function sb(a,b,c){if(0>=a||a>e().length||a&1)return-28;if(pa){if(Atomics.load(w(),a>>2)!=b)return-6;var d=performance.now();c=d+c;for(Atomics.exchange(w(),eb>>2,a);;){d=performance.now();if(d>c)return Atomics.exchange(w(),eb>>2,0),-73;d=Atomics.exchange(w(),eb>>2,0);if(0==d)break;mb();if(Atomics.load(w(),a>>2)!=b)return-6;Atomics.exchange(w(),eb>>2,a)}return 0}a=Atomics.wait(w(),a>>2,b,c);if("timed-out"===a)return-73;if("not-equal"===a)return-6;if("ok"===a)return 0;throw"Atomics.wait returned an unexpected value "+
a;}function tb(){F||E||(ya||(ya={}),ya["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]||(ya["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]=1,N("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread")))}
function ub(a,b){if(!a)return N("pthread_join attempted on a null thread pointer!"),71;if(G&&lb()==a)return N("PThread "+a+" is attempting to join to itself!"),16;if(!G&&vb()==a)return N("Main thread "+a+" is attempting to join to itself!"),16;if(w()[a+8>>2]!==a)return N("pthread_join attempted on thread "+a+", which does not point to a valid thread, or does not exist anymore!"),71;if(Atomics.load(z(),a+60>>2))return N("Attempted to join thread "+a+", which was already detached!"),28;for(tb();;){var c=
Atomics.load(z(),a+0>>2);if(1==c)return b&&(c=Atomics.load(z(),a+88>>2),w()[b>>2]=c),Atomics.store(z(),a+60>>2,1),G?postMessage({cmd:"cleanupThread",thread:a}):fb(a),0;wb();G||mb();sb(a+0,c,G?100:1)}}function xb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}
function yb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=xb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}function zb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function U(a){if("/"===a)return"/";a=yb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function Ab(a,b){return yb(a+"/"+b)}function Bb(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(F)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){M("randomDevice")}}
function Cb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:P.cwd();if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=xb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}
function Db(a,b){function c(k){for(var p=0;p<k.length&&""===k[p];p++);for(var t=k.length-1;0<=t&&""===k[t];t--);return p>t?[]:k.slice(p,t-p+1)}a=Cb(a).substr(1);b=Cb(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),f=d,h=0;h<d;h++)if(a[h]!==b[h]){f=h;break}d=[];for(h=f;h<a.length;h++)d.push("..");d=d.concat(b.slice(f));return d.join("/")}var Eb=[];function Fb(a,b){Eb[a]={input:[],output:[],eb:b};P.Zb(a,Gb)}
var Gb={open:function(a){var b=Eb[a.node.rdev];if(!b)throw new P.X(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.eb.flush(a.tty)},flush:function(a){a.tty.eb.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.eb.sc)throw new P.X(60);for(var f=0,h=0;h<d;h++){try{var k=a.tty.eb.sc(a.tty)}catch(p){throw new P.X(29);}if(void 0===k&&0===f)throw new P.X(6);if(null===k||void 0===k)break;f++;b[c+h]=k}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.eb.Wb)throw new P.X(60);
try{for(var f=0;f<d;f++)a.tty.eb.Wb(a.tty,b[c+f])}catch(h){throw new P.X(29);}d&&(a.node.timestamp=Date.now());return f}},Ib={sc:function(a){if(!a.input.length){var b=null;if(F){var c=Buffer.alloc(256),d=0;try{d=K.readSync(process.stdin.fd,c,0,256,null)}catch(f){if(f.toString().includes("EOF"))d=0;else throw f;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=
readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Hb(b,!0)}return a.input.shift()},Wb:function(a,b){null===b||10===b?(xa(Fa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(xa(Fa(a.output,0)),a.output=[])}},Jb={Wb:function(a,b){null===b||10===b?(N(Fa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(N(Fa(a.output,0)),a.output=[])}};
function Kb(a){a=65536*Math.ceil(a/65536);var b=Lb(65536,a);if(!b)return 0;v().fill(0,b,b+a);return b}
var V={La:null,Ba:function(){return V.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(P.Yc(c)||P.isFIFO(c))throw new P.X(63);V.La||(V.La={dir:{node:{Ia:V.wa.Ia,Ea:V.wa.Ea,lookup:V.wa.lookup,Na:V.wa.Na,rename:V.wa.rename,unlink:V.wa.unlink,rmdir:V.wa.rmdir,readdir:V.wa.readdir,symlink:V.wa.symlink},stream:{Ja:V.ya.Ja}},file:{node:{Ia:V.wa.Ia,Ea:V.wa.Ea},stream:{Ja:V.ya.Ja,read:V.ya.read,write:V.ya.write,jb:V.ya.jb,bb:V.ya.bb,cb:V.ya.cb}},link:{node:{Ia:V.wa.Ia,Ea:V.wa.Ea,readlink:V.wa.readlink},
stream:{}},fc:{node:{Ia:V.wa.Ia,Ea:V.wa.Ea},stream:P.Hc}});c=P.createNode(a,b,c,d);P.Ca(c.mode)?(c.wa=V.La.dir.node,c.ya=V.La.dir.stream,c.xa={}):P.isFile(c.mode)?(c.wa=V.La.file.node,c.ya=V.La.file.stream,c.Aa=0,c.xa=null):P.ab(c.mode)?(c.wa=V.La.link.node,c.ya=V.La.link.stream):P.ub(c.mode)&&(c.wa=V.La.fc.node,c.ya=V.La.fc.stream);c.timestamp=Date.now();a&&(a.xa[b]=c,a.timestamp=c.timestamp);return c},Ld:function(a){return a.xa?a.xa.subarray?a.xa.subarray(0,a.Aa):new Uint8Array(a.xa):new Uint8Array(0)},
mc:function(a,b){var c=a.xa?a.xa.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.xa,a.xa=new Uint8Array(b),0<a.Aa&&a.xa.set(c.subarray(0,a.Aa),0))},qd:function(a,b){if(a.Aa!=b)if(0==b)a.xa=null,a.Aa=0;else{var c=a.xa;a.xa=new Uint8Array(b);c&&a.xa.set(c.subarray(0,Math.min(b,a.Aa)));a.Aa=b}},wa:{Ia:function(a){var b={};b.dev=P.ub(a.mode)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;P.Ca(a.mode)?b.size=4096:P.isFile(a.mode)?b.size=a.Aa:
P.ab(a.mode)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Fc=4096;b.blocks=Math.ceil(b.size/b.Fc);return b},Ea:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&V.qd(a,b.size)},lookup:function(){throw P.Lb[44];},Na:function(a,b,c,d){return V.createNode(a,b,c,d)},rename:function(a,b,c){if(P.Ca(a.mode)){try{var d=P.Ma(b,c)}catch(h){}if(d)for(var f in d.xa)throw new P.X(55);
}delete a.parent.xa[a.name];a.parent.timestamp=Date.now();a.name=c;b.xa[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.xa[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=P.Ma(a,b),d;for(d in c.xa)throw new P.X(55);delete a.xa[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.xa)a.xa.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=V.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(!P.ab(a.mode))throw new P.X(28);
return a.link}},ya:{read:function(a,b,c,d,f){var h=a.node.xa;if(f>=a.node.Aa)return 0;a=Math.min(a.node.Aa-f,d);if(8<a&&h.subarray)b.set(h.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=h[f+d];return a},write:function(a,b,c,d,f,h){b.buffer===e().buffer&&(h=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.xa||a.xa.subarray)){if(h)return a.xa=b.subarray(c,c+d),a.Aa=d;if(0===a.Aa&&0===f)return a.xa=b.slice(c,c+d),a.Aa=d;if(f+d<=a.Aa)return a.xa.set(b.subarray(c,c+d),f),d}V.mc(a,
f+d);if(a.xa.subarray&&b.subarray)a.xa.set(b.subarray(c,c+d),f);else for(h=0;h<d;h++)a.xa[f+h]=b[c+h];a.Aa=Math.max(a.Aa,f+d);return d},Ja:function(a,b,c){1===c?b+=a.position:2===c&&P.isFile(a.node.mode)&&(b+=a.node.Aa);if(0>b)throw new P.X(28);return b},jb:function(a,b,c){V.mc(a.node,b+c);a.node.Aa=Math.max(a.node.Aa,b+c)},bb:function(a,b,c,d,f,h){if(0!==b)throw new P.X(28);if(!P.isFile(a.node.mode))throw new P.X(43);a=a.node.xa;if(h&2||a.buffer!==m){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,
d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;c=Kb(c);if(!c)throw new P.X(48);e().set(a,c)}else d=!1,c=a.byteOffset;return{od:c,Fb:d}},cb:function(a,b,c,d,f){if(!P.isFile(a.node.mode))throw new P.X(43);if(f&2)return 0;V.ya.write(a,b,0,d,c,!1);return 0}}};function Mb(a,b,c){var d="al "+a;sa(a,function(f){assert(f,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(f));d&&Za()},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&Ya()}
var P={root:null,ob:[],jc:{},streams:[],hd:1,Ka:null,ic:"/",Pb:!1,vc:!0,X:null,Lb:{},Sc:null,Ab:0,za:function(a,b){a=Cb(P.cwd(),a);b=b||{};if(!a)return{path:"",node:null};var c={Jb:!0,Yb:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Yb)throw new P.X(32);a=xb(a.split("/").filter(function(k){return!!k}),!1);var f=P.root;c="/";for(d=0;d<a.length;d++){var h=d===a.length-1;if(h&&b.parent)break;f=P.Ma(f,a[d]);c=Ab(c,a[d]);P.Wa(f)&&(!h||h&&b.Jb)&&(f=f.nb.root);if(!h||b.Ha)for(h=0;P.ab(f.mode);)if(f=
P.readlink(c),c=Cb(zb(c),f),f=P.za(c,{Yb:b.Yb}).node,40<h++)throw new P.X(32);}return{path:c,node:f}},Sa:function(a){for(var b;;){if(P.vb(a))return a=a.Ba.wc,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},Ob:function(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%P.Ka.length},tc:function(a){var b=P.Ob(a.parent.id,a.name);a.Ya=P.Ka[b];P.Ka[b]=a},uc:function(a){var b=P.Ob(a.parent.id,a.name);if(P.Ka[b]===a)P.Ka[b]=a.Ya;else for(b=P.Ka[b];b;){if(b.Ya===
a){b.Ya=a.Ya;break}b=b.Ya}},Ma:function(a,b){var c=P.dd(a);if(c)throw new P.X(c,a);for(c=P.Ka[P.Ob(a.id,b)];c;c=c.Ya){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return P.lookup(a,b)},createNode:function(a,b,c,d){a=new P.Ac(a,b,c,d);P.tc(a);return a},Ib:function(a){P.uc(a)},vb:function(a){return a===a.parent},Wa:function(a){return!!a.nb},isFile:function(a){return 32768===(a&61440)},Ca:function(a){return 16384===(a&61440)},ab:function(a){return 40960===(a&61440)},ub:function(a){return 8192===
(a&61440)},Yc:function(a){return 24576===(a&61440)},isFIFO:function(a){return 4096===(a&61440)},isSocket:function(a){return 49152===(a&49152)},Tc:{r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},gd:function(a){var b=P.Tc[a];if("undefined"===typeof b)throw Error("Unknown file open mode: "+a);return b},nc:function(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},Za:function(a,b){if(P.vc)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;
return 0},dd:function(a){var b=P.Za(a,"x");return b?b:a.wa.lookup?0:2},Vb:function(a,b){try{return P.Ma(a,b),20}catch(c){}return P.Za(a,"wx")},wb:function(a,b,c){try{var d=P.Ma(a,b)}catch(f){return f.Da}if(a=P.Za(a,"wx"))return a;if(c){if(!P.Ca(d.mode))return 54;if(P.vb(d)||P.Sa(d)===P.cwd())return 10}else if(P.Ca(d.mode))return 31;return 0},ed:function(a,b){return a?P.ab(a.mode)?32:P.Ca(a.mode)&&("r"!==P.nc(b)||b&512)?31:P.Za(a,P.nc(b)):44},Bc:4096,jd:function(a,b){b=b||P.Bc;for(a=a||0;a<=b;a++)if(!P.streams[a])return a;
throw new P.X(33);},Ua:function(a){return P.streams[a]},Oc:function(a,b,c){P.Eb||(P.Eb=function(){},P.Eb.prototype={object:{get:function(){return this.node},set:function(h){this.node=h}}});var d=new P.Eb,f;for(f in a)d[f]=a[f];a=d;b=P.jd(b,c);a.fd=b;return P.streams[b]=a},Ic:function(a){P.streams[a]=null},Hc:{open:function(a){a.ya=P.Uc(a.node.rdev).ya;a.ya.open&&a.ya.open(a)},Ja:function(){throw new P.X(70);}},Ub:function(a){return a>>8},Pd:function(a){return a&255},Xa:function(a,b){return a<<8|b},
Zb:function(a,b){P.jc[a]={ya:b}},Uc:function(a){return P.jc[a]},rc:function(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push.apply(a,c.ob)}return b},yc:function(a,b){function c(k){P.Ab--;return b(k)}function d(k){if(k){if(!d.Qc)return d.Qc=!0,c(k)}else++h>=f.length&&c(null)}"function"===typeof a&&(b=a,a=!1);P.Ab++;1<P.Ab&&N("warning: "+P.Ab+" FS.syncfs operations in flight at once, probably just doing extra work");var f=P.rc(P.root.Ba),h=0;f.forEach(function(k){if(!k.type.yc)return d(null);
k.type.yc(k,a,d)})},Ba:function(a,b,c){var d="/"===c,f=!c;if(d&&P.root)throw new P.X(10);if(!d&&!f){var h=P.za(c,{Jb:!1});c=h.path;h=h.node;if(P.Wa(h))throw new P.X(10);if(!P.Ca(h.mode))throw new P.X(54);}b={type:a,Ud:b,wc:c,ob:[]};a=a.Ba(b);a.Ba=b;b.root=a;d?P.root=a:h&&(h.nb=b,h.Ba&&h.Ba.ob.push(b));return a},be:function(a){a=P.za(a,{Jb:!1});if(!P.Wa(a.node))throw new P.X(28);a=a.node;var b=a.nb,c=P.rc(b);Object.keys(P.Ka).forEach(function(d){for(d=P.Ka[d];d;){var f=d.Ya;c.includes(d.Ba)&&P.Ib(d);
d=f}});a.nb=null;a.Ba.ob.splice(a.Ba.ob.indexOf(b),1)},lookup:function(a,b){return a.wa.lookup(a,b)},Na:function(a,b,c){var d=P.za(a,{parent:!0}).node;a=U(a);if(!a||"."===a||".."===a)throw new P.X(28);var f=P.Vb(d,a);if(f)throw new P.X(f);if(!d.wa.Na)throw new P.X(63);return d.wa.Na(d,a,b,c)},create:function(a,b){return P.Na(a,(void 0!==b?b:438)&4095|32768,0)},mkdir:function(a,b){return P.Na(a,(void 0!==b?b:511)&1023|16384,0)},Rd:function(a,b){a=a.split("/");for(var c="",d=0;d<a.length;++d)if(a[d]){c+=
"/"+a[d];try{P.mkdir(c,b)}catch(f){if(20!=f.Da)throw f;}}},xb:function(a,b,c){"undefined"===typeof c&&(c=b,b=438);return P.Na(a,b|8192,c)},symlink:function(a,b){if(!Cb(a))throw new P.X(44);var c=P.za(b,{parent:!0}).node;if(!c)throw new P.X(44);b=U(b);var d=P.Vb(c,b);if(d)throw new P.X(d);if(!c.wa.symlink)throw new P.X(63);return c.wa.symlink(c,b,a)},rename:function(a,b){var c=zb(a),d=zb(b),f=U(a),h=U(b);var k=P.za(a,{parent:!0});var p=k.node;k=P.za(b,{parent:!0});k=k.node;if(!p||!k)throw new P.X(44);
if(p.Ba!==k.Ba)throw new P.X(75);var t=P.Ma(p,f);a=Db(a,d);if("."!==a.charAt(0))throw new P.X(28);a=Db(b,c);if("."!==a.charAt(0))throw new P.X(55);try{var n=P.Ma(k,h)}catch(r){}if(t!==n){b=P.Ca(t.mode);if(f=P.wb(p,f,b))throw new P.X(f);if(f=n?P.wb(k,h,b):P.Vb(k,h))throw new P.X(f);if(!p.wa.rename)throw new P.X(63);if(P.Wa(t)||n&&P.Wa(n))throw new P.X(10);if(k!==p&&(f=P.Za(p,"w")))throw new P.X(f);P.uc(t);try{p.wa.rename(t,k,h)}catch(r){throw r;}finally{P.tc(t)}}},rmdir:function(a){var b=P.za(a,{parent:!0}).node;
a=U(a);var c=P.Ma(b,a),d=P.wb(b,a,!0);if(d)throw new P.X(d);if(!b.wa.rmdir)throw new P.X(63);if(P.Wa(c))throw new P.X(10);b.wa.rmdir(b,a);P.Ib(c)},readdir:function(a){a=P.za(a,{Ha:!0}).node;if(!a.wa.readdir)throw new P.X(54);return a.wa.readdir(a)},unlink:function(a){var b=P.za(a,{parent:!0}).node;a=U(a);var c=P.Ma(b,a),d=P.wb(b,a,!1);if(d)throw new P.X(d);if(!b.wa.unlink)throw new P.X(63);if(P.Wa(c))throw new P.X(10);b.wa.unlink(b,a);P.Ib(c)},readlink:function(a){a=P.za(a).node;if(!a)throw new P.X(44);
if(!a.wa.readlink)throw new P.X(28);return Cb(P.Sa(a.parent),a.wa.readlink(a))},stat:function(a,b){a=P.za(a,{Ha:!b}).node;if(!a)throw new P.X(44);if(!a.wa.Ia)throw new P.X(63);return a.wa.Ia(a)},lstat:function(a){return P.stat(a,!0)},chmod:function(a,b,c){a="string"===typeof a?P.za(a,{Ha:!c}).node:a;if(!a.wa.Ea)throw new P.X(63);a.wa.Ea(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},lchmod:function(a,b){P.chmod(a,b,!0)},fchmod:function(a,b){a=P.Ua(a);if(!a)throw new P.X(8);P.chmod(a.node,b)},
chown:function(a,b,c,d){a="string"===typeof a?P.za(a,{Ha:!d}).node:a;if(!a.wa.Ea)throw new P.X(63);a.wa.Ea(a,{timestamp:Date.now()})},lchown:function(a,b,c){P.chown(a,b,c,!0)},fchown:function(a,b,c){a=P.Ua(a);if(!a)throw new P.X(8);P.chown(a.node,b,c)},truncate:function(a,b){if(0>b)throw new P.X(28);a="string"===typeof a?P.za(a,{Ha:!0}).node:a;if(!a.wa.Ea)throw new P.X(63);if(P.Ca(a.mode))throw new P.X(31);if(!P.isFile(a.mode))throw new P.X(28);var c=P.Za(a,"w");if(c)throw new P.X(c);a.wa.Ea(a,{size:b,
timestamp:Date.now()})},Kd:function(a,b){a=P.Ua(a);if(!a)throw new P.X(8);if(0===(a.flags&2097155))throw new P.X(28);P.truncate(a.node,b)},ce:function(a,b,c){a=P.za(a,{Ha:!0}).node;a.wa.Ea(a,{timestamp:Math.max(b,c)})},open:function(a,b,c,d,f){if(""===a)throw new P.X(44);b="string"===typeof b?P.gd(b):b;c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var h=a;else{a=yb(a);try{h=P.za(a,{Ha:!(b&131072)}).node}catch(p){}}var k=!1;if(b&64)if(h){if(b&128)throw new P.X(20);}else h=
P.Na(a,c,0),k=!0;if(!h)throw new P.X(44);P.ub(h.mode)&&(b&=-513);if(b&65536&&!P.Ca(h.mode))throw new P.X(54);if(!k&&(c=P.ed(h,b)))throw new P.X(c);b&512&&P.truncate(h,0);b&=-131713;d=P.Oc({node:h,path:P.Sa(h),flags:b,seekable:!0,position:0,ya:h.ya,Bd:[],error:!1},d,f);d.ya.open&&d.ya.open(d);!A.logReadFiles||b&1||(P.Xb||(P.Xb={}),a in P.Xb||(P.Xb[a]=1));return d},close:function(a){if(P.mb(a))throw new P.X(8);a.Nb&&(a.Nb=null);try{a.ya.close&&a.ya.close(a)}catch(b){throw b;}finally{P.Ic(a.fd)}a.fd=
null},mb:function(a){return null===a.fd},Ja:function(a,b,c){if(P.mb(a))throw new P.X(8);if(!a.seekable||!a.ya.Ja)throw new P.X(70);if(0!=c&&1!=c&&2!=c)throw new P.X(28);a.position=a.ya.Ja(a,b,c);a.Bd=[];return a.position},read:function(a,b,c,d,f){if(0>d||0>f)throw new P.X(28);if(P.mb(a))throw new P.X(8);if(1===(a.flags&2097155))throw new P.X(8);if(P.Ca(a.node.mode))throw new P.X(31);if(!a.ya.read)throw new P.X(28);var h="undefined"!==typeof f;if(!h)f=a.position;else if(!a.seekable)throw new P.X(70);
b=a.ya.read(a,b,c,d,f);h||(a.position+=b);return b},write:function(a,b,c,d,f,h){if(0>d||0>f)throw new P.X(28);if(P.mb(a))throw new P.X(8);if(0===(a.flags&2097155))throw new P.X(8);if(P.Ca(a.node.mode))throw new P.X(31);if(!a.ya.write)throw new P.X(28);a.seekable&&a.flags&1024&&P.Ja(a,0,2);var k="undefined"!==typeof f;if(!k)f=a.position;else if(!a.seekable)throw new P.X(70);b=a.ya.write(a,b,c,d,f,h);k||(a.position+=b);return b},jb:function(a,b,c){if(P.mb(a))throw new P.X(8);if(0>b||0>=c)throw new P.X(28);
if(0===(a.flags&2097155))throw new P.X(8);if(!P.isFile(a.node.mode)&&!P.Ca(a.node.mode))throw new P.X(43);if(!a.ya.jb)throw new P.X(138);a.ya.jb(a,b,c)},bb:function(a,b,c,d,f,h){if(0!==(f&2)&&0===(h&2)&&2!==(a.flags&2097155))throw new P.X(2);if(1===(a.flags&2097155))throw new P.X(2);if(!a.ya.bb)throw new P.X(43);return a.ya.bb(a,b,c,d,f,h)},cb:function(a,b,c,d,f){return a&&a.ya.cb?a.ya.cb(a,b,c,d,f):0},Td:function(){return 0},Qb:function(a,b,c){if(!a.ya.Qb)throw new P.X(59);return a.ya.Qb(a,b,c)},
readFile:function(a,b){b=b||{};b.flags=b.flags||0;b.encoding=b.encoding||"binary";if("utf8"!==b.encoding&&"binary"!==b.encoding)throw Error('Invalid encoding type "'+b.encoding+'"');var c,d=P.open(a,b.flags);a=P.stat(a).size;var f=new Uint8Array(a);P.read(d,f,0,a,0);"utf8"===b.encoding?c=Fa(f,0):"binary"===b.encoding&&(c=f);P.close(d);return c},writeFile:function(a,b,c){c=c||{};c.flags=c.flags||577;a=P.open(a,c.flags,c.mode);if("string"===typeof b){var d=new Uint8Array(Ha(b)+1);b=Ga(b,d,0,d.length);
P.write(a,d,0,b,void 0,c.Gc)}else if(ArrayBuffer.isView(b))P.write(a,b,0,b.byteLength,void 0,c.Gc);else throw Error("Unsupported data type");P.close(a)},cwd:function(){return P.ic},chdir:function(a){a=P.za(a,{Ha:!0});if(null===a.node)throw new P.X(44);if(!P.Ca(a.node.mode))throw new P.X(54);var b=P.Za(a.node,"x");if(b)throw new P.X(b);P.ic=a.path},Kc:function(){P.mkdir("/tmp");P.mkdir("/home");P.mkdir("/home/web_user")},Jc:function(){P.mkdir("/dev");P.Zb(P.Xa(1,3),{read:function(){return 0},write:function(b,
c,d,f){return f}});P.xb("/dev/null",P.Xa(1,3));Fb(P.Xa(5,0),Ib);Fb(P.Xa(6,0),Jb);P.xb("/dev/tty",P.Xa(5,0));P.xb("/dev/tty1",P.Xa(6,0));var a=Bb();P.Ra("/dev","random",a);P.Ra("/dev","urandom",a);P.mkdir("/dev/shm");P.mkdir("/dev/shm/tmp")},Mc:function(){P.mkdir("/proc");var a=P.mkdir("/proc/self");P.mkdir("/proc/self/fd");P.Ba({Ba:function(){var b=P.createNode(a,"fd",16895,73);b.wa={lookup:function(c,d){var f=P.Ua(+d);if(!f)throw new P.X(8);c={parent:null,Ba:{wc:"fake"},wa:{readlink:function(){return f.path}}};
return c.parent=c}};return b}},{},"/proc/self/fd")},Nc:function(){A.stdin?P.Ra("/dev","stdin",A.stdin):P.symlink("/dev/tty","/dev/stdin");A.stdout?P.Ra("/dev","stdout",null,A.stdout):P.symlink("/dev/tty","/dev/stdout");A.stderr?P.Ra("/dev","stderr",null,A.stderr):P.symlink("/dev/tty1","/dev/stderr");P.open("/dev/stdin",0);P.open("/dev/stdout",1);P.open("/dev/stderr",1)},lc:function(){P.X||(P.X=function(a,b){this.node=b;this.sd=function(c){this.Da=c};this.sd(a);this.message="FS error"},P.X.prototype=
Error(),P.X.prototype.constructor=P.X,[44].forEach(function(a){P.Lb[a]=new P.X(a);P.Lb[a].stack="<generic error, no stack>"}))},vd:function(){P.lc();P.Ka=Array(4096);P.Ba(V,{},"/");P.Kc();P.Jc();P.Mc();P.Sc={MEMFS:V}},lb:function(a,b,c){P.lb.Pb=!0;P.lc();A.stdin=a||A.stdin;A.stdout=b||A.stdout;A.stderr=c||A.stderr;P.Nc()},Wd:function(){P.lb.Pb=!1;var a=A._fflush;a&&a(0);for(a=0;a<P.streams.length;a++){var b=P.streams[a];b&&P.close(b)}},Mb:function(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c},Jd:function(a,
b){a=P.Hb(a,b);return a.exists?a.object:null},Hb:function(a,b){try{var c=P.za(a,{Ha:!b});a=c.path}catch(f){}var d={vb:!1,exists:!1,error:0,name:null,path:null,object:null,kd:!1,md:null,ld:null};try{c=P.za(a,{parent:!0}),d.kd=!0,d.md=c.path,d.ld=c.node,d.name=U(a),c=P.za(a,{Ha:!b}),d.exists=!0,d.path=c.path,d.object=c.node,d.name=c.node.name,d.vb="/"===c.path}catch(f){d.error=f.Da}return d},Gd:function(a,b){a="string"===typeof a?a:P.Sa(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=
Ab(a,c);try{P.mkdir(d)}catch(f){}a=d}}return d},Lc:function(a,b,c,d,f){a=Ab("string"===typeof a?a:P.Sa(a),b);return P.create(a,P.Mb(d,f))},hc:function(a,b,c,d,f,h){a=b?Ab("string"===typeof a?a:P.Sa(a),b):a;d=P.Mb(d,f);f=P.create(a,d);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var k=c.length;b<k;++b)a[b]=c.charCodeAt(b);c=a}P.chmod(f,d|146);a=P.open(f,577);P.write(a,c,0,c.length,0,h);P.close(a);P.chmod(f,d)}return f},Ra:function(a,b,c,d){a=Ab("string"===typeof a?a:P.Sa(a),b);b=P.Mb(!!c,
!!d);P.Ra.Ub||(P.Ra.Ub=64);var f=P.Xa(P.Ra.Ub++,0);P.Zb(f,{open:function(h){h.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(h,k,p,t){for(var n=0,r=0;r<t;r++){try{var y=c()}catch(C){throw new P.X(29);}if(void 0===y&&0===n)throw new P.X(6);if(null===y||void 0===y)break;n++;k[p+r]=y}n&&(h.node.timestamp=Date.now());return n},write:function(h,k,p,t){for(var n=0;n<t;n++)try{d(k[p+n])}catch(r){throw new P.X(29);}t&&(h.node.timestamp=Date.now());return n}});return P.xb(a,
b,f)},oc:function(a){if(a.Rb||a.Zc||a.link||a.xa)return!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ra)try{a.xa=Hb(ra(a.url),!0),a.Aa=a.xa.length}catch(b){throw new P.X(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");},Fd:function(a,b,c,d,f){function h(){this.Sb=!1;this.Qa=
[]}h.prototype.get=function(n){if(!(n>this.length-1||0>n)){var r=n%this.chunkSize;return this.Va(n/this.chunkSize|0)[r]}};h.prototype.Cd=function(n){this.Va=n};h.prototype.ec=function(){var n=new XMLHttpRequest;n.open("HEAD",c,!1);n.send(null);if(!(200<=n.status&&300>n.status||304===n.status))throw Error("Couldn't load "+c+". Status: "+n.status);var r=Number(n.getResponseHeader("Content-length")),y,C=(y=n.getResponseHeader("Accept-Ranges"))&&"bytes"===y;n=(y=n.getResponseHeader("Content-Encoding"))&&
"gzip"===y;var l=1048576;C||(l=r);var u=this;u.Cd(function(x){var H=x*l,R=(x+1)*l-1;R=Math.min(R,r-1);if("undefined"===typeof u.Qa[x]){var Nc=u.Qa;if(H>R)throw Error("invalid range ("+H+", "+R+") or no bytes requested!");if(R>r-1)throw Error("only "+r+" bytes available! programmer error!");var I=new XMLHttpRequest;I.open("GET",c,!1);r!==l&&I.setRequestHeader("Range","bytes="+H+"-"+R);"undefined"!=typeof Uint8Array&&(I.responseType="arraybuffer");I.overrideMimeType&&I.overrideMimeType("text/plain; charset=x-user-defined");
I.send(null);if(!(200<=I.status&&300>I.status||304===I.status))throw Error("Couldn't load "+c+". Status: "+I.status);H=void 0!==I.response?new Uint8Array(I.response||[]):Hb(I.responseText||"",!0);Nc[x]=H}if("undefined"===typeof u.Qa[x])throw Error("doXHR failed!");return u.Qa[x]});if(n||!r)l=r=1,l=r=this.Va(0).length,xa("LazyFiles on gzip forces download of the whole file when length is accessed");this.Dc=r;this.Cc=l;this.Sb=!0};if("undefined"!==typeof XMLHttpRequest){if(!E)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";
var k=new h;Object.defineProperties(k,{length:{get:function(){this.Sb||this.ec();return this.Dc}},chunkSize:{get:function(){this.Sb||this.ec();return this.Cc}}});k={Rb:!1,xa:k}}else k={Rb:!1,url:c};var p=P.Lc(a,b,k,d,f);k.xa?p.xa=k.xa:k.url&&(p.xa=null,p.url=k.url);Object.defineProperties(p,{Aa:{get:function(){return this.xa.length}}});var t={};Object.keys(p.ya).forEach(function(n){var r=p.ya[n];t[n]=function(){P.oc(p);return r.apply(null,arguments)}});t.read=function(n,r,y,C,l){P.oc(p);n=n.node.xa;
if(l>=n.length)return 0;C=Math.min(n.length-l,C);if(n.slice)for(var u=0;u<C;u++)r[y+u]=n[l+u];else for(u=0;u<C;u++)r[y+u]=n.get(l+u);return C};p.ya=t;return p},Hd:function(a,b,c,d,f,h,k,p,t,n){function r(C){function l(x){n&&n();p||P.hc(a,b,x,d,f,t);h&&h();Za()}var u=!1;A.preloadPlugins.forEach(function(x){!u&&x.canHandle(y)&&(x.handle(C,y,l,function(){k&&k();Za()}),u=!0)});u||l(C)}Nb.lb();var y=b?Cb(Ab(a,b)):a;Ya();"string"==typeof c?Mb(c,function(C){r(C)},k):r(c)},indexedDB:function(){return window.indexedDB||
window.mozIndexedDB||window.webkitIndexedDB||window.msIndexedDB},cc:function(){return"EM_FS_"+window.location.pathname},dc:20,ib:"FILE_DATA",Yd:function(a,b,c){b=b||function(){};c=c||function(){};var d=P.indexedDB();try{var f=d.open(P.cc(),P.dc)}catch(h){return c(h)}f.onupgradeneeded=function(){xa("creating db");f.result.createObjectStore(P.ib)};f.onsuccess=function(){var h=f.result.transaction([P.ib],"readwrite"),k=h.objectStore(P.ib),p=0,t=0,n=a.length;a.forEach(function(r){r=k.put(P.Hb(r).object.xa,
r);r.onsuccess=function(){p++;p+t==n&&(0==t?b():c())};r.onerror=function(){t++;p+t==n&&(0==t?b():c())}});h.onerror=c};f.onerror=c},Od:function(a,b,c){b=b||function(){};c=c||function(){};var d=P.indexedDB();try{var f=d.open(P.cc(),P.dc)}catch(h){return c(h)}f.onupgradeneeded=c;f.onsuccess=function(){var h=f.result;try{var k=h.transaction([P.ib],"readonly")}catch(y){c(y);return}var p=k.objectStore(P.ib),t=0,n=0,r=a.length;a.forEach(function(y){var C=p.get(y);C.onsuccess=function(){P.Hb(y).exists&&P.unlink(y);
P.hc(zb(y),U(y),C.result,!0,!0,!0);t++;t+n==r&&(0==n?b():c())};C.onerror=function(){n++;t+n==r&&(0==n?b():c())}});k.onerror=c};f.onerror=c}},Ob={};
function Pb(a,b){var c=P.stat;try{var d=c(a)}catch(f){if(f&&f.node&&yb(a)!==yb(P.Sa(f.node)))return-54;throw f;}w()[b>>2]=d.dev;w()[b+4>>2]=0;w()[b+8>>2]=d.ino;w()[b+12>>2]=d.mode;w()[b+16>>2]=d.nlink;w()[b+20>>2]=d.uid;w()[b+24>>2]=d.gid;w()[b+28>>2]=d.rdev;w()[b+32>>2]=0;T=[d.size>>>0,(S=d.size,1<=+Math.abs(S)?0<S?(Math.min(+Math.floor(S/4294967296),4294967295)|0)>>>0:~~+Math.ceil((S-+(~~S>>>0))/4294967296)>>>0:0)];w()[b+40>>2]=T[0];w()[b+44>>2]=T[1];w()[b+48>>2]=4096;w()[b+52>>2]=d.blocks;w()[b+
56>>2]=d.atime.getTime()/1E3|0;w()[b+60>>2]=0;w()[b+64>>2]=d.mtime.getTime()/1E3|0;w()[b+68>>2]=0;w()[b+72>>2]=d.ctime.getTime()/1E3|0;w()[b+76>>2]=0;T=[d.ino>>>0,(S=d.ino,1<=+Math.abs(S)?0<S?(Math.min(+Math.floor(S/4294967296),4294967295)|0)>>>0:~~+Math.ceil((S-+(~~S>>>0))/4294967296)>>>0:0)];w()[b+80>>2]=T[0];w()[b+84>>2]=T[1];return 0}var Qb=void 0;function Rb(){Qb+=4;return w()[Qb-4>>2]}function W(a){a=P.Ua(a);if(!a)throw new P.X(8);return a}
function Sb(a,b,c){if(G)return X(2,1,a,b,c);Qb=c;try{var d=W(a);switch(b){case 0:var f=Rb();return 0>f?-28:P.open(d.path,d.flags,0,f).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return f=Rb(),d.flags|=f,0;case 12:return f=Rb(),g.buffer!=m&&q(g.buffer),La[f+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return w()[Tb()>>2]=28,-1;default:return-28}}catch(h){return"undefined"!==typeof P&&h instanceof P.X||M(h),-h.Da}}
function Ub(a,b){if(G)return X(3,1,a,b);try{var c=W(a);return Pb(c.path,b)}catch(d){return"undefined"!==typeof P&&d instanceof P.X||M(d),-d.Da}}
function Vb(a,b,c){if(G)return X(4,1,a,b,c);Qb=c;try{var d=W(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var f=Rb();return w()[f>>2]=0;case 21520:return d.tty?-28:-59;case 21531:return f=Rb(),P.Qb(d,b,f);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:M("bad ioctl syscall "+b)}}catch(h){return"undefined"!==typeof P&&h instanceof P.X||M(h),-h.Da}}
function Wb(a,b,c,d,f,h){if(G)return X(5,1,a,b,c,d,f,h);try{a:{h<<=12;var k=!1;if(0!==(d&16)&&0!==a%65536)var p=-28;else{if(0!==(d&32)){var t=Kb(b);if(!t){p=-48;break a}k=!0}else{var n=P.Ua(f);if(!n){p=-8;break a}var r=P.bb(n,a,b,h,c,d);t=r.od;k=r.Fb}Ob[t]={cd:t,$c:b,Fb:k,fd:f,nd:c,flags:d,offset:h};p=t}}return p}catch(y){return"undefined"!==typeof P&&y instanceof P.X||M(y),-y.Da}}
function Xb(a,b){if(G)return X(6,1,a,b);try{var c=Ob[a];if(0!==b&&c){if(b===c.$c){var d=P.Ua(c.fd);if(d&&c.nd&2){var f=c.flags,h=c.offset,k=v().slice(a,a+b);P.cb(d,k,h,b,f)}Ob[a]=null;c.Fb&&jb(c.cd)}var p=0}else p=-28;return p}catch(t){return"undefined"!==typeof P&&t instanceof P.X||M(t),-t.Da}}function Yb(a,b,c){if(G)return X(7,1,a,b,c);Qb=c;try{var d=O(a),f=c?Rb():0;return P.open(d,b,f).fd}catch(h){return"undefined"!==typeof P&&h instanceof P.X||M(h),-h.Da}}
function Zb(a,b){if(G)return X(8,1,a,b);try{return a=O(a),Pb(a,b)}catch(c){return"undefined"!==typeof P&&c instanceof P.X||M(c),-c.Da}}function $b(a){if(G)return X(9,1,a);noExitRuntime=!1;Ra=0;hb(a)}function X(a,b){for(var c=arguments.length-2,d=ac(),f=Ja(8*c),h=f>>3,k=0;k<c;k++){var p=arguments[2+k];ea()[h+k]=p}c=bc(a,c,f,b);pb(d);return c}var cc=[],dc=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];
function ec(a){a=2<a?O(a):a;return dc[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}
function fc(a,b,c){var d=ec(a);if(!d)return-4;d.tb&&(w()[d.tb>>2]=b,w()[d.tb+4>>2]=c);if(d.xc||!d.Ed)d.xc&&(d=d.xc),a=!1,d.sb&&d.sb.rb&&(a=d.sb.rb.getParameter(2978),a=0===a[0]&&0===a[1]&&a[2]===d.width&&a[3]===d.height),d.width=b,d.height=c,a&&d.sb.rb.viewport(0,0,b,c);else{if(d.tb){d=w()[d.tb+8>>2];a=a?O(a):"";var f=ac(),h=Ja(12),k=0;if(a){k=Ha(a)+1;var p=gc(k);Ga(a,v(),p,k);k=p}w()[h>>2]=k;w()[h+4>>2]=b;w()[h+8>>2]=c;hc(0,d,657457152,0,k,h);pb(f);return 1}return-4}return 0}
function ic(a,b,c){return G?X(10,1,a,b,c):fc(a,b,c)}function jc(a){if(!Ba)try{if(a(),G&&!va())try{G?kc(Ca):hb(Ca)}catch(b){ib(b)}}catch(b){ib(b)}}function lc(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,f,h){b.drawArraysInstancedANGLE(c,d,f,h)},a.drawElementsInstanced=function(c,d,f,h,k){b.drawElementsInstancedANGLE(c,d,f,h,k)})}
function mc(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function nc(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
function oc(a,b){a.qc||(a.qc=a.getContext,a.getContext=function(d,f){f=a.qc(d,f);return"webgl"==d==f instanceof WebGLRenderingContext?f:null});var c=a.getContext("webgl",b);return c?pc(c,b):0}function pc(a,b){var c=gc(8);w()[c+4>>2]=lb();var d={Md:c,attributes:b,version:b.bd,rb:a};a.canvas&&(a.canvas.sb=d);("undefined"===typeof b.kc||b.kc)&&qc(d);return c}
function qc(a){a||(a=rc);if(!a.Wc){a.Wc=!0;var b=a.rb;lc(b);mc(b);nc(b);b.Id=b.getExtension("EXT_disjoint_timer_query");b.Sd=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var rc,sc=["default","low-power","high-performance"],tc={};
function uc(){if(!vc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:na||"./this.program"},b;for(b in tc)void 0===tc[b]?delete a[b]:a[b]=tc[b];var c=[];for(b in a)c.push(b+"="+a[b]);vc=c}return vc}var vc;
function wc(a,b){if(G)return X(11,1,a,b);var c=0;uc().forEach(function(d,f){var h=b+c;f=w()[a+4*f>>2]=h;for(h=0;h<d.length;++h)e()[f++>>0]=d.charCodeAt(h);e()[f>>0]=0;c+=d.length+1});return 0}function xc(a,b){if(G)return X(12,1,a,b);var c=uc();w()[a>>2]=c.length;var d=0;c.forEach(function(f){d+=f.length+1});w()[b>>2]=d;return 0}function yc(a){if(G)return X(13,1,a);try{var b=W(a);P.close(b);return 0}catch(c){return"undefined"!==typeof P&&c instanceof P.X||M(c),c.Da}}
function zc(a,b){if(G)return X(14,1,a,b);try{var c=W(a),d=c.tty?2:P.Ca(c.mode)?3:P.ab(c.mode)?7:4;e()[b>>0]=d;return 0}catch(f){return"undefined"!==typeof P&&f instanceof P.X||M(f),f.Da}}function Ac(a,b,c,d){if(G)return X(15,1,a,b,c,d);try{a:{for(var f=W(a),h=a=0;h<c;h++){var k=w()[b+8*h>>2],p=w()[b+(8*h+4)>>2],t=P.read(f,e(),k,p,void 0);if(0>t){var n=-1;break a}a+=t;if(t<p)break}n=a}w()[d>>2]=n;return 0}catch(r){return"undefined"!==typeof P&&r instanceof P.X||M(r),r.Da}}
function Bc(a,b,c,d,f){if(G)return X(16,1,a,b,c,d,f);try{var h=W(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;P.Ja(h,a,d);T=[h.position>>>0,(S=h.position,1<=+Math.abs(S)?0<S?(Math.min(+Math.floor(S/4294967296),4294967295)|0)>>>0:~~+Math.ceil((S-+(~~S>>>0))/4294967296)>>>0:0)];w()[f>>2]=T[0];w()[f+4>>2]=T[1];h.Nb&&0===a&&0===d&&(h.Nb=null);return 0}catch(k){return"undefined"!==typeof P&&k instanceof P.X||M(k),k.Da}}
function Cc(a,b,c,d){if(G)return X(17,1,a,b,c,d);try{a:{for(var f=W(a),h=a=0;h<c;h++){var k=w()[b+8*h>>2],p=w()[b+(8*h+4)>>2],t=P.write(f,e(),k,p,void 0);if(0>t){var n=-1;break a}a+=t}n=a}w()[d>>2]=n;return 0}catch(r){return"undefined"!==typeof P&&r instanceof P.X||M(r),r.Da}}function Dc(a){return 0===a%4&&(0!==a%100||0===a%400)}function Ec(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Fc=[31,29,31,30,31,30,31,31,30,31,30,31],Gc=[31,28,31,30,31,30,31,31,30,31,30,31];
function Hc(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Dc(a.getFullYear())?Fc:Gc)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Ic(a,b,c,d){function f(l,u,x){for(l="number"===typeof l?l.toString():l||"";l.length<u;)l=x[0]+l;return l}function h(l,u){return f(l,u,"0")}function k(l,u){function x(R){return 0>R?-1:0<R?1:0}var H;0===(H=x(l.getFullYear()-u.getFullYear()))&&0===(H=x(l.getMonth()-u.getMonth()))&&(H=x(l.getDate()-u.getDate()));return H}function p(l){switch(l.getDay()){case 0:return new Date(l.getFullYear()-1,11,29);case 1:return l;case 2:return new Date(l.getFullYear(),0,3);case 3:return new Date(l.getFullYear(),
0,2);case 4:return new Date(l.getFullYear(),0,1);case 5:return new Date(l.getFullYear()-1,11,31);case 6:return new Date(l.getFullYear()-1,11,30)}}function t(l){l=Hc(new Date(l.Fa+1900,0,1),l.Db);var u=new Date(l.getFullYear()+1,0,4),x=p(new Date(l.getFullYear(),0,4));u=p(u);return 0>=k(x,l)?0>=k(u,l)?l.getFullYear()+1:l.getFullYear():l.getFullYear()-1}var n=w()[d+40>>2];d={yd:w()[d>>2],xd:w()[d+4>>2],Bb:w()[d+8>>2],qb:w()[d+12>>2],hb:w()[d+16>>2],Fa:w()[d+20>>2],Cb:w()[d+24>>2],Db:w()[d+28>>2],$d:w()[d+
32>>2],wd:w()[d+36>>2],zd:n?O(n):""};c=O(c);n={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var r in n)c=c.replace(new RegExp(r,"g"),n[r]);var y="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
C="January February March April May June July August September October November December".split(" ");n={"%a":function(l){return y[l.Cb].substring(0,3)},"%A":function(l){return y[l.Cb]},"%b":function(l){return C[l.hb].substring(0,3)},"%B":function(l){return C[l.hb]},"%C":function(l){return h((l.Fa+1900)/100|0,2)},"%d":function(l){return h(l.qb,2)},"%e":function(l){return f(l.qb,2," ")},"%g":function(l){return t(l).toString().substring(2)},"%G":function(l){return t(l)},"%H":function(l){return h(l.Bb,
2)},"%I":function(l){l=l.Bb;0==l?l=12:12<l&&(l-=12);return h(l,2)},"%j":function(l){return h(l.qb+Ec(Dc(l.Fa+1900)?Fc:Gc,l.hb-1),3)},"%m":function(l){return h(l.hb+1,2)},"%M":function(l){return h(l.xd,2)},"%n":function(){return"\n"},"%p":function(l){return 0<=l.Bb&&12>l.Bb?"AM":"PM"},"%S":function(l){return h(l.yd,2)},"%t":function(){return"\t"},"%u":function(l){return l.Cb||7},"%U":function(l){var u=new Date(l.Fa+1900,0,1),x=0===u.getDay()?u:Hc(u,7-u.getDay());l=new Date(l.Fa+1900,l.hb,l.qb);return 0>
k(x,l)?h(Math.ceil((31-x.getDate()+(Ec(Dc(l.getFullYear())?Fc:Gc,l.getMonth()-1)-31)+l.getDate())/7),2):0===k(x,u)?"01":"00"},"%V":function(l){var u=new Date(l.Fa+1901,0,4),x=p(new Date(l.Fa+1900,0,4));u=p(u);var H=Hc(new Date(l.Fa+1900,0,1),l.Db);return 0>k(H,x)?"53":0>=k(u,H)?"01":h(Math.ceil((x.getFullYear()<l.Fa+1900?l.Db+32-x.getDate():l.Db+1-x.getDate())/7),2)},"%w":function(l){return l.Cb},"%W":function(l){var u=new Date(l.Fa,0,1),x=1===u.getDay()?u:Hc(u,0===u.getDay()?1:7-u.getDay()+1);l=
new Date(l.Fa+1900,l.hb,l.qb);return 0>k(x,l)?h(Math.ceil((31-x.getDate()+(Ec(Dc(l.getFullYear())?Fc:Gc,l.getMonth()-1)-31)+l.getDate())/7),2):0===k(x,u)?"01":"00"},"%y":function(l){return(l.Fa+1900).toString().substring(2)},"%Y":function(l){return l.Fa+1900},"%z":function(l){l=l.wd;var u=0<=l;l=Math.abs(l)/60;return(u?"+":"-")+String("0000"+(l/60*100+l%60)).slice(-4)},"%Z":function(l){return l.zd},"%%":function(){return"%"}};for(r in n)c.includes(r)&&(c=c.replace(new RegExp(r,"g"),n[r](d)));r=Hb(c,
!1);if(r.length>b)return 0;Ka(r,a);return r.length-1}function Jc(a){try{a()}catch(b){M(b)}}var Y=0,Z=null,Kc=0,Lc=[],Mc={},Oc={},Pc=0,Qc=null,Rc=[];function Sc(a){var b={},c;for(c in a)(function(d){var f=a[d];b[d]="function"===typeof f?function(){Lc.push(d);try{return f.apply(null,arguments)}finally{if(!Ba){var h=Lc.pop();assert(h===d);Z&&1===Y&&0===Lc.length&&(Ra+=1,Y=0,Jc(A._asyncify_stop_unwind),"undefined"!==typeof Fibers&&Fibers.ae())}}}:f})(c);return b}
function Tc(){var a=gc(4108),b=a+12;w()[a>>2]=b;w()[a+4>>2]=b+4096;b=Lc[0];var c=Mc[b];void 0===c&&(c=Pc++,Mc[b]=c,Oc[c]=b);b=c;w()[a+8>>2]=b;return a}function Uc(){var a=Z;a=w()[a+8>>2];a=A.asm[Oc[a]];--Ra;return a()}
function Vc(a){if(!Ba){if(0===Y){var b=!1,c=!1;a(function(d){if(!Ba&&(Kc=d||0,b=!0,c)){Y=2;Jc(function(){A._asyncify_start_rewind(Z)});"undefined"!==typeof Nb&&Nb.Tb.pc&&Nb.Tb.resume();d=!1;try{var f=Uc()}catch(p){f=p,d=!0}var h=!1;if(!Z){var k=Qc;k&&(Qc=null,(d?k.reject:k.resolve)(f),h=!0)}if(d&&!h)throw f;}});c=!0;b||(Y=1,Z=Tc(),Jc(function(){A._asyncify_start_unwind(Z)}),"undefined"!==typeof Nb&&Nb.Tb.pc&&Nb.Tb.pause())}else 2===Y?(Y=0,Jc(A._asyncify_stop_rewind),jb(Z),Z=null,Rc.forEach(function(d){jc(d)})):
M("invalid state: "+Y);return Kc}}function Wc(a){return Vc(function(b){a().then(b)})}function Xc(a,b,c,d){a||(a=this);this.parent=a;this.Ba=a.Ba;this.nb=null;this.id=P.hd++;this.name=b;this.mode=c;this.wa={};this.ya={};this.rdev=d}
Object.defineProperties(Xc.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Zc:{get:function(){return P.Ca(this.mode)}},Rb:{get:function(){return P.ub(this.mode)}}});P.Ac=Xc;P.vd();var Nb,Yc=[null,function(a,b){if(G)return X(1,1,a,b)},Sb,Ub,Vb,Wb,Xb,Yb,Zb,$b,ic,wc,xc,yc,zc,Ac,Bc,Cc];
function Hb(a,b){var c=Array(Ha(a)+1);a=Ga(a,c,0,c.length);b&&(c.length=a);return c}
var bd={c:function(a,b,c,d){M("Assertion failed: "+O(a)+", at: "+[b?O(b):"unknown filename",c,d?O(d):"unknown function"])},p:function(a,b){Zc(a,b)},s:function(a,b){B.ac.push(function(){dynCall_vi.apply(null,[a,b])})},Q:function(a){$c(a,!E,1);B.zc()},j:function(a,b,c,d){if("undefined"===typeof SharedArrayBuffer)return N("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;var f=[];if(G&&0===f.length)return ad(687865856,a,b,c,d);var h=0,k=0;if(b&&-1!=b){var p=w()[b>>
2];p+=81920;h=w()[b+8>>2];k=0!==w()[b+12>>2]}else p=2097152;(b=0==h)?h=Lb(16,p):(h-=p,assert(0<h));a={$a:h,fb:p,Gb:b,detached:k,ud:c,yb:a,kb:d,Ad:f};return G?(a.Dd="spawnThread",postMessage(a,f),0):nb(a)},M:function(){postMessage({cmd:"detachedExit"})},n:function(){for(;0<B.ac.length;)B.ac.pop()()},J:function(a,b){return ub(a,b)},k:Sb,F:Ub,A:Vb,G:function(){return 0},H:Wb,I:Xb,l:Yb,E:Zb,S:function(a,b){if(a==b)postMessage({cmd:"processQueuedMainThreadWork"});else if(G)postMessage({targetThread:a,
cmd:"processThreadQueue"});else{a=(a=B.Ga[a])&&a.worker;if(!a)return;a.postMessage({cmd:"processThreadQueue"})}return 1},b:function(){M()},u:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=rb();else return w()[Tb()>>2]=28,-1;w()[b>>2]=a/1E3|0;w()[b+4>>2]=a%1E3*1E6|0;return 0},B:tb,i:function(){},C:$b,f:sb,d:db,g:rb,r:function(a,b,c){v().copyWithin(a,b,b+c)},N:function(a,b,c){cc.length=b;c>>=3;for(var d=0;d<b;d++)cc[d]=ea()[c+d];return(0>a?cb[-a-1]:Yc[a]).apply(null,cc)},t:function(a){var b=
v().length;a>>>=0;if(a<=b||2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{g.grow(Math.min(2147483648,d)-m.byteLength+65535>>>16);q(g.buffer);var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},O:function(a,b,c){return ec(a)?fc(a,b,c):ic(a,b,c)},m:function(){},q:function(){},R:function(a,b,c){Ra+=1;return setTimeout(function(){--Ra;jc(function(){dynCall_vi.apply(null,[a,c])})},b)},K:function(){throw"unwind";
},L:function(){return Wc(async()=>{var a=await A.queue.get();const b=Ha(a)+1,c=gc(b);Ga(a,v(),c,b);return c})},P:function(a,b){b>>=2;var c=w()[b+6];b={alpha:!!w()[b],depth:!!w()[b+1],stencil:!!w()[b+2],antialias:!!w()[b+3],premultipliedAlpha:!!w()[b+4],preserveDrawingBuffer:!!w()[b+5],powerPreference:sc[c],failIfMajorPerformanceCaveat:!!w()[b+7],bd:w()[b+8],Qd:w()[b+9],kc:w()[b+10],Rc:w()[b+11],Vd:w()[b+12],Xd:w()[b+13]};a=ec(a);return!a||b.Rc?0:oc(a,b)},w:wc,x:xc,e:gb,h:yc,D:zc,z:Ac,o:Bc,y:Cc,a:g||
A.wasmMemory,v:function(a,b,c,d){return Ic(a,b,c,d)}};
(function(){function a(h,k){h=h.exports;h=Sc(h);A.asm=h;Oa.unshift(A.asm.T);B.bc.push(A.asm.W);Aa=k;G||Za()}function b(h){a(h.instance,h.module)}function c(h){return bb().then(function(k){return WebAssembly.instantiate(k,d)}).then(function(k){return k}).then(h,function(k){N("failed to asynchronously prepare wasm: "+k);M(k)})}var d={a:bd};G||Ya();if(A.instantiateWasm)try{var f=A.instantiateWasm(d,a);return f=Sc(f)}catch(h){return N("Module.instantiateWasm callback failed with error: "+h),!1}(function(){return za||
"function"!==typeof WebAssembly.instantiateStreaming||$a()||"function"!==typeof fetch?c(b):fetch(Q,{credentials:"same-origin"}).then(function(h){return WebAssembly.instantiateStreaming(h,d).then(b,function(k){N("wasm streaming compile failed: "+k);N("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ia);return{}})();A.___wasm_call_ctors=function(){return(A.___wasm_call_ctors=A.asm.T).apply(null,arguments)};
var Zc=A._main=function(){return(Zc=A._main=A.asm.U).apply(null,arguments)},jb=A._free=function(){return(jb=A._free=A.asm.V).apply(null,arguments)};A._emscripten_tls_init=function(){return(A._emscripten_tls_init=A.asm.W).apply(null,arguments)};A._emscripten_current_thread_process_queued_calls=function(){return(A._emscripten_current_thread_process_queued_calls=A.asm.Y).apply(null,arguments)};
var vb=A._emscripten_main_browser_thread_id=function(){return(vb=A._emscripten_main_browser_thread_id=A.asm.Z).apply(null,arguments)},ad=A._emscripten_sync_run_in_main_thread_4=function(){return(ad=A._emscripten_sync_run_in_main_thread_4=A.asm._).apply(null,arguments)},mb=A._emscripten_main_thread_process_queued_calls=function(){return(mb=A._emscripten_main_thread_process_queued_calls=A.asm.$).apply(null,arguments)},bc=A._emscripten_run_in_main_runtime_thread_js=function(){return(bc=A._emscripten_run_in_main_runtime_thread_js=
A.asm.aa).apply(null,arguments)},hc=A.__emscripten_call_on_thread=function(){return(hc=A.__emscripten_call_on_thread=A.asm.ba).apply(null,arguments)},kc=A.__emscripten_thread_exit=function(){return(kc=A.__emscripten_thread_exit=A.asm.ca).apply(null,arguments)};A.___pthread_tsd_run_dtors=function(){return(A.___pthread_tsd_run_dtors=A.asm.da).apply(null,arguments)};
var gc=A._malloc=function(){return(gc=A._malloc=A.asm.ea).apply(null,arguments)},lb=A._pthread_self=function(){return(lb=A._pthread_self=A.asm.fa).apply(null,arguments)},$c=A.__emscripten_thread_init=function(){return($c=A.__emscripten_thread_init=A.asm.ga).apply(null,arguments)},wb=A._pthread_testcancel=function(){return(wb=A._pthread_testcancel=A.asm.ha).apply(null,arguments)};A._emscripten_proxy_main=function(){return(A._emscripten_proxy_main=A.asm.ia).apply(null,arguments)};
var Tb=A.___errno_location=function(){return(Tb=A.___errno_location=A.asm.ja).apply(null,arguments)},ac=A.stackSave=function(){return(ac=A.stackSave=A.asm.ka).apply(null,arguments)},pb=A.stackRestore=function(){return(pb=A.stackRestore=A.asm.la).apply(null,arguments)},Ja=A.stackAlloc=function(){return(Ja=A.stackAlloc=A.asm.ma).apply(null,arguments)},ob=A._emscripten_stack_set_limits=function(){return(ob=A._emscripten_stack_set_limits=A.asm.na).apply(null,arguments)},Lb=A._memalign=function(){return(Lb=
A._memalign=A.asm.oa).apply(null,arguments)},dynCall_vi=A.dynCall_vi=function(){return(dynCall_vi=A.dynCall_vi=A.asm.pa).apply(null,arguments)},qb=A.dynCall_ii=function(){return(qb=A.dynCall_ii=A.asm.qa).apply(null,arguments)},dynCall_v=A.dynCall_v=function(){return(dynCall_v=A.dynCall_v=A.asm.ra).apply(null,arguments)};A._asyncify_start_unwind=function(){return(A._asyncify_start_unwind=A.asm.sa).apply(null,arguments)};
A._asyncify_stop_unwind=function(){return(A._asyncify_stop_unwind=A.asm.ta).apply(null,arguments)};A._asyncify_start_rewind=function(){return(A._asyncify_start_rewind=A.asm.ua).apply(null,arguments)};A._asyncify_stop_rewind=function(){return(A._asyncify_stop_rewind=A.asm.va).apply(null,arguments)};var kb=A.__emscripten_allow_main_runtime_queued_calls=12065532,eb=A.__emscripten_main_thread_futex=13281072;A.keepRuntimeAlive=va;A.FS=P;A.PThread=B;A.PThread=B;A.wasmMemory=g;A.ExitStatus=ua;var cd;
function ua(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Xa=function dd(){cd||ed();cd||(Xa=dd)};
function ed(a){function b(){if(!cd&&(cd=!0,A.calledRun=!0,!Ba)){Sa();G||Ta(Pa);ha(A);if(A.onRuntimeInitialized)A.onRuntimeInitialized();if(fd){var c=a,d=A._emscripten_proxy_main;c=c||[];var f=c.length+1,h=Ja(4*(f+1));w()[h>>2]=Ia(na);for(var k=1;k<f;k++)w()[(h>>2)+k]=Ia(c[k-1]);w()[(h>>2)+f]=0;d(f,h)}if(!G){if(A.postRun)for("function"==typeof A.postRun&&(A.postRun=[A.postRun]);A.postRun.length;)c=A.postRun.shift(),Qa.unshift(c);Ta(Qa)}}}a=a||ma;if(!(0<Va))if(G)ha(A),Sa(),postMessage({cmd:"loaded"});
else{if(!G){if(A.preRun)for("function"==typeof A.preRun&&(A.preRun=[A.preRun]);A.preRun.length;)Ua();Ta(Na)}0<Va||(A.setStatus?(A.setStatus("Running..."),setTimeout(function(){setTimeout(function(){A.setStatus("")},1);b()},1)):b())}}A.run=ed;function hb(a){Ca=a;if(G)throw postMessage({cmd:"exitProcess",returnCode:a}),new ua(a);va()||B.$b();Ca=a;if(!va()){B.$b();if(A.onExit)A.onExit(a);Ba=!0}oa(a,new ua(a))}if(A.preInit)for("function"==typeof A.preInit&&(A.preInit=[A.preInit]);0<A.preInit.length;)A.preInit.pop()();
var fd=!0;A.noInitialRun&&(fd=!1);G&&(noExitRuntime=!1,B.Xc());ed();


  return Stockfish.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = Stockfish;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return Stockfish; });
else if (typeof exports === 'object')
  exports["Stockfish"] = Stockfish;
